---
- hosts: 127.0.0.1
  tasks:
   - name: Checkout subversion repository to specified folder
     subversion:
       repo: https://svn.ekenya.co.ke/svn/KENYA/Swivel_Ecommerce/frontend/content/dist
       username: jkibet
       password:
       checkout: yes
       update: yes
       in_place: yes
       dest: /mnt/c/Users/jkibet/Music/test2/
